### ISSUE TITLE
Turn on pyright and correct tests

### ISSUE THREAD

**Issue by benzlokzik** [benzlokzik-university/telegram-bot-anycode-recognizer#14]
Don't forget turn on pyright ([.github/workflows/lint_and_types.yml](https://github.com/benzlokzik/telegram-bot-anycode-recognizer/tree/master/.github/workflows/lint_and_types.yml))

```yaml
    - name: Check types by pyright
      run: |
        poetry run pyright
```

and correct tests
